import { TheHeader } from '@/components/TheHeader'
import './globals.css'
import { TheFooter } from '@/components/TheFooter'



export const metadata = {
  title: 'Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body className='body'>
      <TheHeader/>
        <main className='container'>{children}</main>
      <TheFooter/>
      </body>
    </html>
  )
}
